database:
  type: sqlite # sqlite or mysql
  mysql:
    host: localhost
    port: 3306
    database: wefriends
    username: root
    password: ""

redis:
  enabled: false
  host: localhost
  port: 6379
  password: ""
  channel: wefriends:events

server:
  name: lobby

cross-server:
  enabled: true
  sync-interval: 30
  notification-timeout: 5

limits:
  max-friends: 200
  max-party-size: 8

messages:
  usage:
    friend: "<gray>/friend <add|accept|deny|remove|list|toggle|chat>"
    friend_add: "<gray>/friend add <player>"
    friend_accept: "<gray>/friend accept <player>"
    friend_deny: "<gray>/friend deny <player>"
    friend_remove: "<gray>/friend remove <player>"
    fchat: "<gray>/fchat <message>"
    fmsg: "<gray>/fmsg <friend> <message>"
    party: "<gray>/party <create|invite|accept|deny|leave|kick|promote|transfer|disband|chat>"
    party_invite: "<gray>/party invite <player>"
    party_accept: "<gray>/party accept <player>"
    party_deny: "<gray>/party deny <player>"
    party_kick: "<gray>/party kick <player>"
    party_promote: "<gray>/party promote <player>"
    party_transfer: "<gray>/party transfer <player>"
    pc: "<gray>/pc <message>"

  error:
    self_friend: "<red>You cannot friend yourself."
    player_not_found: "<red>Player <white>%player%</white> not found."

  friend:
    requests_off: "<yellow>%friend%</yellow> has friend requests <red>disabled</red>."
    already: "<yellow>%friend%</yellow> is already your friend."
    accepted: "<green>You are now friends with <yellow>%friend%</yellow>."
    accepted_other: "<yellow>%friend%</yellow> accepted your friend request."
    denied: "<red>You denied the request from <yellow>%friend%</yellow>."
    removed: "<gray>You removed <yellow>%friend%</yellow> from your friends."
    not_friends: "<red>You are not friends with <yellow>%friend%</yellow>."
    list_header: "<gray>Friends: <green>%online%</green>/<yellow>%total%</yellow> online"
    list_empty: "<gray>You have no friends added."
    list_online: "<green>Online:</green> <white>%friends%</white>"
    list_offline: "<gray>Offline:</gray> <white>%friends%</white>"
    no_requests: "<gray>You have no pending friend requests."
    requests_header: "<gray>Pending requests (<yellow>%count%</yellow>):"
    request_item: "<gray>- <yellow>%player%</yellow> <click:run_command:/friend accept %player%><green>[Accept]</green></click> <click:run_command:/friend deny %player%><red>[Deny]</red></click>"
    request_received: "<yellow>%player%</yellow> sent you a friend request!"
    request_sent: "<gray>Friend request sent to <yellow>%friend%</yellow>."
    toggle_on: "<green>Friend requests enabled."
    toggle_off: "<red>Friend requests disabled."

  party:
    created: "<green>Party created! Invite friends with <yellow>/party invite <player></yellow>."
    not_in_party: "<red>You are not in a party."
    not_leader: "<red>You must be the party leader to do this."
    target_in_party: "<red><yellow>%player%</yellow> is already in a party."
    not_friend: "<red>You can only invite friends to your party."
    invite_received: "<yellow>%player%</yellow> invited you to their party! <click:run_command:/party accept %player%><green>[Accept]</green></click> <click:run_command:/party deny %player%><red>[Deny]</red></click>"
    invite_sent: "<gray>Party invite sent to <yellow>%player%</yellow>."
    no_invite: "<red>No party invite from <yellow>%player%</yellow>."
    joined: "<green>You joined the party!"
    member_joined: "<green><yellow>%player%</yellow> joined the party!"
    member_left: "<yellow><yellow>%player%</yellow> left the party."
    denied: "<gray>Party invite denied."
    left: "<gray>You left the party."
    kicked: "<gray>You kicked <yellow>%player%</yellow> from the party."
    promoted: "<gray>You promoted <yellow>%player%</yellow> to party leader."
    disbanded: "<red>Party disbanded."
    cross_server_invite: "<yellow>%player%</yellow> invited you to their party from <yellow>%server%</yellow>! <click:run_command:/party accept %player% %server%><green>[Accept]</green></click> <click:run_command:/party deny %player% %server%><red>[Deny]</red></click>"
    cross_server_joined: "<green>You joined the party from <yellow>%server%</yellow>!"
    cross_server_member_joined: "<green><yellow>%player%</yellow> joined the party from <yellow>%server%</yellow>!"
    cross_server_member_left: "<yellow><yellow>%player%</yellow> left the party from <yellow>%server%</yellow>."
    cross_server_kicked: "<gray>You kicked <yellow>%player%</yellow> from the party from <yellow>%server%</yellow>."
    cross_server_promoted: "<gray>You promoted <yellow>%player%</yellow> to party leader from <yellow>%server%</yellow>."

  actionbar:
    friend_join: "<gray>Your friend <green>%player%</green> joined."
    friend_quit: "<gray>Your friend <red>%player%</red> left."
    friend_request: "<gray>Friend request from <yellow>%player%</yellow>!"
    party_invite: "<gray>Party invite from <yellow>%player%</yellow>!"

  chat:
    friend_format: "<yellow>[F] <green>%player%</green><gray>: </gray>%message%"
    friend_msg_receive: "<yellow>[F->You] <green>%player%</green><gray>: </gray>%message%"
    friend_msg_send: "<yellow>[You->F] <green>%friend%</green><gray>: </gray>%message%"
    party_format: "<aqua>[P] <green>%player%</green><gray>: </gray>%message%"

  spy:
    friend_on: "<gray><i>[Spy]</i> Friend chat spy <green>enabled</green>."
    friend_off: "<gray><i>[Spy]</i> Friend chat spy <red>disabled</red>."
    party_on: "<gray><i>[Spy]</i> Party chat spy <green>enabled</green>."
    party_off: "<gray><i>[Spy]</i> Party chat spy <red>disabled</red>."
    all_on: "<gray><i>[Spy]</i> All spy modes <green>enabled</green>."
    all_off: "<gray><i>[Spy]</i> All spy modes <red>disabled</red>."
